### ISSUE TITLE
Historie a pdbox

### ISSUE THREAD

**Issue by zipper** [peckadesign/pd.ajax#13]
Po konzultaci s projekťáky upravíme chování historie při otevírání a zavírání pdboxu. Nově se bude pdbox chovat jedním ze tří způsobů na základě data atributu elementu, který pdbox otevírá:

1. Při otevření pdboxu se vytvoří nový stav, jakákoli interakce uvnitř pdboxu bude tento stav nahrazovat (tj.  bude stále jeden stav v historii pro všechny v tomto pdboxu navštívené stránky). Zavření pdboxu nebude vytvářet další nový stav, ale půjde v historii zpět a zavře pdbox. Tj. po zavření uživatel pdbox může otevřít tlačítkem "vpřed" prohlížeče.

2. Otevření pdboxu vytvoří nový stav, jakékoli další kroky uvnitř pdboxu budou také vytvářet nový (pokud odkazy uvnitř nemají historii vyplnutou explicitně). Po zavření se chová stejně, jako v případě (1).

3. Stávající chování, tj. stejné jako (2), ale v případě zavření se vytváří nový stav a tlačítko "zpět" tudíž otevírá znovu pdbox.

Zůstane zachovaná možnost vypnout historii úplně, stejně jako nyní. V takovém případě při otevřeném pdboxu zmáčknutí tlačítka zpět nejen zavře pdbox, ale i přejde na předchozí stránku.

V rámci realizace možná sloučím možnosti (1) a (2) do jedné a rozlišení chování bude na kodérovi v rámci samotného pdboxu (tj. bude-li chtít, aby se stav do historie nezapsal jako nový, bude muset takovému odkazu ručně přidat nějaké extension, které to bude dělat).

cc @peckadesign/projektaci

**Comment by zipper** [comment]
Je to připraveno, prosím o pokud možno důkladnou kontrolu. Body (1) a (2) jsou nakonec sloučeny, respektive je realizován jen bod (2). Pokud je žádoucí chování z bodu jedna, nejde to udělat snadno automaticky čistě přes `pdbox`, protože ten neřeší historii, tu řeší primárně extension `history`. Pokud by to mělo být čistě v `pdbox` extension, bylo by nutné jej relativně výrazně přepsat, aby řešil veškerou historii sám. To se mi zdá příliš složité, proto je to vyřešeno jinak. Pokud je žádoucí, aby se stav nahrazoval, je nutné vypnout `history` ručně a místo něj použít `replaceState`, který už máme na Gantu nebo Hudy pro přepínání variant. Nově bude přímo součástí `pd.ajax` knihoven. Více v příkladu na nasazeném projektu. Výhodou je možnost chování zkombinovat (tj. některé stavy v pdboxu se zapíší jako nové, jiné se jen nahrazují).

V knihovně pd.ajax:
- Ve větvi `13-pdbox-historie`
- PR #14 

Připraveno k testu na projektu Hudy na detailu produktu:
- Ve větvi `pd.ajax-13-pdbox-historie`
- PR https://github.com/peckadesign/Hudy2017/pull/1607
- http://test1607.hudy2017.peckadesign.com/guide-5-0-jacket-men?variant=30887&size=141589
- Historie je zapnutá pro tři pdboxy:
  - "Jak vybrat správnou velikost" - odpovídá (2), na tomto produktu je ještě upravena tabulka tak, aby obsahovala ještě další ajaxový odkaz a bylo tak vidět propisování do historie, když se zapíše více stavů. Tady je žádoucí, aby v historii byly všechny stavy, jak je uživatel prošel.
  - "Rezervovat na prodejně" - zde je vidět naopak chování z bodu (1), kde v historii je vždy pouze poslední stav pdboxu daný tím, kam uživatel došel odesíláním formulářů. Tady není žádoucí, aby po odeslání byl v historii i krok s výběrem prodejny (už proto, že jakmile je "objednávka" odeslaná, je potřeba začít znovu).
  - "Do košíku" - toto je čistě pro test a je zde ukázka chování (3), tj. po zavření se vytváří nový stav. Toto chování nebude prakticky nikde žádoucí, je tu nachystáno jen pro účel testu, aby bylo vidět, že to stále je možné a že to funguje. Teoreticky by to mohlo zůstat na Korálcích. Z Hudy to pak odebereme, respektive změníme na (2).

Na testu je zároveň i nasazená oprava titulků v Chrome historii (viz https://github.com/vojtech-dobes/nette.ajax.js/issues/151).

**Comment by petrzdansky** [comment]
@Qitek85 Vítku, je to nasazené primárně na Hudy. Mohl by jsi to prosím otestovat. Případně Vláďa nebo Patrik?

**Comment by Qitek85** [comment]
@zipper @petrzdansky 
Za mě to je OK a všechny 3 scénáře se chovají tak, jak je popsáno.

**Comment by zipper** [comment]
Vydáno ve verzi 1.4.0, viz https://github.com/peckadesign/pd.ajax/releases/tag/1.4.0.
