### ISSUE TITLE
Zavření TB a historie

### ISSUE THREAD

**Issue by zipper** [peckadesign/pd.ajax#3]
- [ ] Detail produktu -> předkošík s historií v TB -> zavřít křížkem -> 2x zpět => duplicitní stav detailu produktu
- [ ] Při zavření TB, kde je historie vypnutá se zduplikuje stav

**Comment by petrzdansky** [comment]
@vitkutny Víťo, mohli byste se prosím domluvit s @zipper Radkem na společné úpravě. Podle včerejší konzultace by mělo stačit tam vrátit nějakou část od tebe, kterou jsi původně kvůli jinému úkolu zrušil.

@zipper Radku, případně za Víťou zajdi a dořešte to co nejdřív, prosím.

**Comment by zipper** [comment]
Toto se toho netýká, je to čistě JS problém.
