### ISSUE TITLE
Zrušení probíhajícího xhr requestu při zavření pdboxu

### ISSUE THREAD

**Issue by zipper** [peckadesign/pd.ajax#7]
Při zavření pdboxu dochází k zrušení probíhajícího requestu. Nynější implementace má dva problémy:
- [x] Při zavření pdboxu se zruší i `xhr` request, který s pdboxem nemusí souviset (probíhající na pozadí na základě akce v pdboxu, např. přepočítávání košíku pod pdboxem).
- [x] Při každém requestu se naváže nový callback po zrušení xhr, i když je daný xhr dávno dokončený. Je potřeba toto upravit podobným způsobem jako `pushOriginalApplied` nebo jako rušení `xhr` v extension `abort`.

**Comment by zipper** [comment]
Po úpravách teoreticky řešitelné přes vypnutí extension `pdbox` na daném AJAXu. Je nutné upravit chování automatického přidávání class na vše (filtr na vypnuté extension) a navázání `abort` na `afterClose`.

**Comment by Spilky** [comment]
V tuto chvíli není možné vypnout extension `unique`, protože request je zrušen vždy v extension `pdbox`.

**Comment by zipper** [comment]
Mělo by být opraveno v PR #14.

**Comment by zipper** [comment]
Vydáno ve verzi 1.4.0, viz https://github.com/peckadesign/pd.ajax/releases/tag/1.4.0.
